### ISSUE TITLE
The example doesn't work

### ISSUE THREAD

**Issue by bblanchon** [kapouer/postinstall#10]
Hi,

My setup:

* Windows 11
* Node 20.9.0
* NPM 9.2.0

My package.json (directly copied from the README):

```json
{
  "dependencies": {
    "jquery": "3",
    "postinstall": "*"
  },
  "postinstall": {
    "jquery/dist/jquery.slim.min.js": "link public/js/jquery.min.js",
    "jquery/dist/jquery.slim.min.map": "link public/js/jquery.min.js.map"
  },
  "scripts": {
    "postinstall": "postinstall"
  }
}
```

See also [package-lock.json](https://github.com/kapouer/postinstall/files/13683934/package-lock.json)

When I run `npm install`, I get the following error:

```c++
Error: link public/js/jquery.min.js but no files found at E:\demo_postinstall\node_modules\jquery\dist\jquery.slim.min.js
```

Despite what the error message says, the file is there.

Best regards,
Benoit

**Comment by kapouer** [comment]
Thanks, but this software has never been tested on windows.
